version: "3.8"

services:

  app:
    build: .
    container_name: grocery_app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prom-grocery
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"   # Prometheus UI
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-grocery
    ports:
      - "3000:3000"   # Grafana UI
    depends_on:
      - prometheus
    restart: unless-stopped
