global:
  scrape_interval: 5s  # how often Prometheus scrapes targets

scrape_configs:
  - job_name: "grocery-list-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:8000"
